plugins {
    id 'java'
    id 'maven-publish'
    id 'com.enonic.defaults' version '2.1.7'
    id 'com.enonic.xp.base'
}

repositories {
    mavenLocal()
    mavenCentral()
    xp.enonicRepo('dev')
}

dependencies {
    compileOnly xplibs.api.portal
    implementation libs.jmustache

    testImplementation "com.enonic.xp:testing:${xpVersion}"
    testImplementation platform( libs.junit.bom )
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
    testImplementation libs.mockito.core
}

test {
    useJUnitPlatform()
}
