plugins {
    id 'java'
    id 'maven-publish'
    id 'com.enonic.defaults' version '2.1.6'
    id 'com.enonic.xp.base'
}

repositories {
    mavenLocal()
    mavenCentral()
    xp.enonicRepo()
}

dependencies {
    compileOnly xplibs.api.portal
    implementation 'com.samskivert:jmustache:1.16'

    testImplementation "com.enonic.xp:testing:${xpVersion}"
    testImplementation platform( 'org.junit:junit-bom:5.13.4' )
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.mockito:mockito-core:5+'
}

test {
    useJUnitPlatform()
}
